-- Insert sample doctors into the profiles table
INSERT INTO public.profiles (
  user_id, 
  first_name, 
  last_name, 
  role, 
  specialization, 
  consultation_fee, 
  is_active, 
  medical_license_number, 
  experience_years, 
  bio,
  phone,
  is_verified
) VALUES 
  (
    gen_random_uuid(),
    'Sarah',
    'Johnson',
    'doctor',
    'Cardiology',
    800,
    true,
    'MD12345',
    12,
    'Experienced cardiologist specializing in preventive care and heart disease management. Board certified with expertise in echocardiography and stress testing.',
    '+1-555-0101',
    true
  ),
  (
    gen_random_uuid(),
    'Michael',
    'Chen',
    'doctor',
    'Dermatology',
    600,
    true,
    'MD23456',
    8,
    'Dermatologist with focus on skin cancer prevention, acne treatment, and cosmetic dermatology. Fellowship trained in Mohs surgery.',
    '+1-555-0102',
    true
  ),
  (
    gen_random_uuid(),
    'Emily',
    'Rodriguez',
    'doctor',
    'Family Medicine',
    500,
    true,
    'MD34567',
    15,
    'Family medicine physician providing comprehensive primary care for patients of all ages. Special interest in preventive medicine and chronic disease management.',
    '+1-555-0103',
    true
  ),
  (
    gen_random_uuid(),
    'David',
    'Thompson',
    'doctor',
    'Orthopedics',
    900,
    true,
    'MD45678',
    10,
    'Orthopedic surgeon specializing in sports medicine and joint replacement. Team physician for local sports teams.',
    '+1-555-0104',
    true
  ),
  (
    gen_random_uuid(),
    'Lisa',
    'Patel',
    'doctor',
    'Pediatrics',
    550,
    true,
    'MD56789',
    7,
    'Board-certified pediatrician providing comprehensive care for infants, children, and adolescents. Special focus on developmental pediatrics.',
    '+1-555-0105',
    true
  ),
  (
    gen_random_uuid(),
    'Robert',
    'Anderson',
    'doctor',
    'Internal Medicine',
    650,
    true,
    'MD67890',
    20,
    'Internal medicine physician with extensive experience in hospital medicine and outpatient care. Subspecialty training in infectious diseases.',
    '+1-555-0106',
    true
  ),
  (
    gen_random_uuid(),
    'Jessica',
    'Kim',
    'doctor',
    'Psychiatry',
    750,
    true,
    'MD78901',
    9,
    'Psychiatrist specializing in anxiety, depression, and ADHD treatment. Provides both medication management and psychotherapy.',
    '+1-555-0107',
    true
  ),
  (
    gen_random_uuid(),
    'William',
    'Davis',
    'doctor',
    'Neurology',
    850,
    true,
    'MD89012',
    14,
    'Neurologist with expertise in headache disorders, epilepsy, and movement disorders. Fellowship trained in clinical neurophysiology.',
    '+1-555-0108',
    true
  );